#!/usr/bin/env python3
from __future__ import annotations

import argparse
import hashlib
import re
import sys
from pathlib import Path
from typing import Sequence

CHANNEL_TO_TOKEN = {
    "stable": "foundry",
    "alpha": "foundry@alpha",
    "beta": "foundry@beta",
    "rc": "foundry@rc",
}
ALL_TOKENS = tuple(CHANNEL_TO_TOKEN.values())
PRERELEASE_STATUS_RE = re.compile(r"^(alpha|beta|rc)[1-9][0-9]*$")
SHA256_RE = re.compile(r"^[0-9a-fA-F]{64}$")


def channel_for_status(status: str) -> str:
    if status == "stable":
        return "stable"

    match = PRERELEASE_STATUS_RE.fullmatch(status)
    if match is not None:
        return match.group(1)

    raise ValueError(f"Release status '{status}' does not map to a Homebrew cask channel.")


def token_for_status(status: str) -> str:
    return CHANNEL_TO_TOKEN[channel_for_status(status)]


def conflict_tokens(token: str) -> list[str]:
    if token not in ALL_TOKENS:
        raise ValueError(f"Unknown Homebrew cask token '{token}'.")
    return [candidate for candidate in ALL_TOKENS if candidate != token]


def validate_sha256(sha256: str) -> str:
    if SHA256_RE.fullmatch(sha256) is None:
        raise ValueError("SHA-256 must be a 64-character hexadecimal digest.")
    return sha256.lower()


def asset_sha256(asset_path: Path) -> str:
    if not asset_path.is_file():
        raise ValueError(f"release asset does not exist: {asset_path}")

    digest = hashlib.sha256()
    with asset_path.open("rb") as asset_file:
        for chunk in iter(lambda: asset_file.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def cask_filename(token: str) -> str:
    if token not in ALL_TOKENS:
        raise ValueError(f"Unknown Homebrew cask token '{token}'.")
    return f"{token}.rb"


def render_cask(*, token: str, version: str, macos_sha256: str, linux_sha256: str) -> str:
    if not version:
        raise ValueError("Version must not be empty.")

    macos_digest = validate_sha256(macos_sha256)
    linux_digest = validate_sha256(linux_sha256)
    conflicts = ", ".join(f'"{conflict}"' for conflict in conflict_tokens(token))

    return f"""# This file was generated by Foundry release automation. DO NOT EDIT.
cask "{token}" do
  version "{version}"

  name "Foundry"
  desc "Game engine and editor with Foundry Script"
  homepage "https://github.com/cafecito-games/Foundry"

  livecheck do
    skip "Auto-generated on release."
  end

  conflicts_with cask: [{conflicts}]

  on_macos do
    sha256 "{macos_digest}"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{{version}}/Foundry_v#{{version}}_macos.universal.zip"

    app "Foundry.app"
    binary "#{{appdir}}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"
  end

  on_linux do
    sha256 "{linux_digest}"
    url "https://github.com/cafecito-games/Foundry/releases/download/v#{{version}}/Foundry_v#{{version}}_linux.x86_64.zip"

    binary "foundry.linuxbsd.editor.x86_64", target: "foundry"
  end

end
"""


def write_cask(*, status: str, version: str, macos_sha256: str, linux_sha256: str, output_dir: Path) -> Path:
    token = token_for_status(status)
    output_dir.mkdir(parents=True, exist_ok=True)
    cask_path = output_dir / cask_filename(token)
    cask_path.write_text(
        render_cask(token=token, version=version, macos_sha256=macos_sha256, linux_sha256=linux_sha256)
    )
    return cask_path


def parse_args(argv: Sequence[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Generate a Foundry Homebrew cask for a release channel.")
    parser.add_argument(
        "--status", required=True, help="Resolved Foundry release status, e.g. stable, alpha1, beta2, rc1."
    )
    parser.add_argument("--version", required=True, help="Release version used in the GitHub Release asset name.")
    parser.add_argument(
        "--output-dir", required=True, type=Path, help="Directory where the generated cask should be written."
    )

    macos_checksum = parser.add_mutually_exclusive_group(required=True)
    macos_checksum.add_argument("--macos-asset", type=Path, help="Path to the macOS release asset to checksum.")
    macos_checksum.add_argument("--macos-sha256", help="Precomputed SHA-256 for the macOS release asset.")

    linux_checksum = parser.add_mutually_exclusive_group(required=True)
    linux_checksum.add_argument("--linux-asset", type=Path, help="Path to the Linux x86_64 release asset to checksum.")
    linux_checksum.add_argument("--linux-sha256", help="Precomputed SHA-256 for the Linux x86_64 release asset.")
    return parser.parse_args(argv)


def main(argv: Sequence[str]) -> int:
    args = parse_args(argv)

    try:
        macos_digest = (
            asset_sha256(args.macos_asset) if args.macos_asset is not None else validate_sha256(args.macos_sha256)
        )
        linux_digest = (
            asset_sha256(args.linux_asset) if args.linux_asset is not None else validate_sha256(args.linux_sha256)
        )
        cask_path = write_cask(
            status=args.status,
            version=args.version,
            macos_sha256=macos_digest,
            linux_sha256=linux_digest,
            output_dir=args.output_dir,
        )
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    print(cask_path)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
