<Project>
  <ItemGroup>
    <!-- $(FoundryProjectDir) is defined by Godot.NET.Sdk -->
    <CompilerVisibleProperty Include="FoundryDisabledSourceGenerators" />
    <CompilerVisibleProperty Include="FoundryProjectDir" />
    <CompilerVisibleProperty Include="FoundryProjectDirBase64" />
    <CompilerVisibleProperty Include="FoundrySourceGenerators" />
    <CompilerVisibleProperty Include="IsGodotToolsProject" />
  </ItemGroup>
</Project>
