#!/usr/bin/env python3
"""Check the generated Homebrew cask and the release workflow's tap wiring.

`find_workflow_wiring_violations` is pure over the workflow text and is driven
by `misc/checks/tests/test_check_homebrew_cask.py`; the rest of the check
executes `.github/scripts/generate_homebrew_cask.py` for real.
"""

from __future__ import annotations

import hashlib
import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / ".github/scripts/generate_homebrew_cask.py"
RELEASE_WORKFLOW = REPO_ROOT / ".github/workflows/release.yml"


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    sys.exit(1)


def load_generator():
    if not GENERATOR.is_file():
        fail(f"could not load generator module at {GENERATOR}")

    spec = importlib.util.spec_from_file_location("generate_homebrew_cask", GENERATOR)
    if spec is None or spec.loader is None:
        fail(f"could not load generator module at {GENERATOR}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def require_equal(actual, expected, message: str) -> None:
    if actual != expected:
        fail(f"{message}: expected {expected!r}, got {actual!r}")


def require_contains(haystack: str, needle: str, message: str) -> None:
    if needle not in haystack:
        fail(f"{message}: missing {needle!r}")


def require_absent(haystack: str, needle: str, message: str) -> None:
    if needle in haystack:
        fail(f"{message}: unexpected {needle!r}")


def require_raises(expected_message: str, callback) -> None:
    try:
        callback()
    except ValueError as exc:
        if expected_message not in str(exc):
            fail(f"wrong error message: expected {expected_message!r} in {exc!r}")
        return
    fail(f"expected ValueError containing {expected_message!r}")


def check_status_maps_to_cask_tokens(generator) -> None:
    cases = {
        "stable": "foundry",
        "alpha1": "foundry@alpha",
        "alpha27": "foundry@alpha",
        "beta1": "foundry@beta",
        "beta12": "foundry@beta",
        "rc1": "foundry@rc",
        "rc8": "foundry@rc",
    }
    for status, expected_token in cases.items():
        require_equal(generator.token_for_status(status), expected_token, f"token for {status}")


def check_status_mapping_rejects_unknown_statuses(generator) -> None:
    for status in ["dev", "alpha0", "preview1", "rc", "stable1", ""]:
        require_raises(
            "does not map to a Homebrew cask channel", lambda status=status: generator.token_for_status(status)
        )


def check_render_stable_cask(generator) -> None:
    cask = generator.render_cask(
        token="foundry",
        version="0.1.0",
        macos_sha256="0" * 64,
        linux_sha256="1" * 64,
    )

    required = [
        "# This file was generated by Foundry release automation. DO NOT EDIT.",
        'cask "foundry" do',
        'version "0.1.0"',
        'name "Foundry"',
        'desc "Game engine and editor with Foundry Script"',
        'homepage "https://github.com/cafecito-games/Foundry"',
        'skip "Auto-generated on release."',
        'conflicts_with cask: ["foundry@alpha", "foundry@beta", "foundry@rc"]',
        "on_macos do",
        'sha256 "0000000000000000000000000000000000000000000000000000000000000000"',
        'url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_macos.universal.zip"',
        'app "Foundry.app"',
        'binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"',
        "on_linux do",
        'sha256 "1111111111111111111111111111111111111111111111111111111111111111"',
        'url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_linux.x86_64.zip"',
        'binary "foundry.linuxbsd.editor.x86_64", target: "foundry"',
    ]
    for snippet in required:
        require_contains(cask, snippet, "stable cask")

    require_absent(cask, 'conflicts_with cask: ["foundry",', "stable cask should not conflict with itself")
    require_absent(cask, 'conflicts_with cask: "foundry@alpha"', "stable cask should use one conflicts array")


def check_render_alpha_cask(generator) -> None:
    cask = generator.render_cask(
        token="foundry@alpha",
        version="0.1.0-alpha.3",
        macos_sha256="a" * 64,
        linux_sha256="c" * 64,
    )

    required = [
        'cask "foundry@alpha" do',
        'version "0.1.0-alpha.3"',
        'sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"',
        'sha256 "cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc"',
        'conflicts_with cask: ["foundry", "foundry@beta", "foundry@rc"]',
        'binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"',
        'binary "foundry.linuxbsd.editor.x86_64", target: "foundry"',
    ]
    for snippet in required:
        require_contains(cask, snippet, "alpha cask")

    require_absent(
        cask, 'conflicts_with cask: ["foundry", "foundry@alpha"', "alpha cask should not conflict with itself"
    )
    require_absent(cask, 'conflicts_with cask: "foundry"', "alpha cask should use one conflicts array")


def check_cli_writes_expected_cask_and_checksum(generator) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        casks_dir = tmp_path / "Casks"
        macos_asset = tmp_path / "Foundry_v0.1.0-beta.2_macos.universal.zip"
        linux_asset = tmp_path / "Foundry_v0.1.0-beta.2_linux.x86_64.zip"
        macos_asset.write_bytes(b"fake foundry macos app archive")
        linux_asset.write_bytes(b"fake foundry linux editor archive")
        expected_macos_sha = hashlib.sha256(macos_asset.read_bytes()).hexdigest()
        expected_linux_sha = hashlib.sha256(linux_asset.read_bytes()).hexdigest()

        result = subprocess.run(
            [
                sys.executable,
                str(GENERATOR),
                "--status",
                "beta2",
                "--version",
                "0.1.0-beta.2",
                "--macos-asset",
                str(macos_asset),
                "--linux-asset",
                str(linux_asset),
                "--output-dir",
                str(casks_dir),
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )

        cask_path = casks_dir / "foundry@beta.rb"
        require_equal(result.stdout.strip(), str(cask_path), "generator stdout")
        if result.stderr:
            fail(f"generator should not write stderr on success: {result.stderr}")
        if not cask_path.is_file():
            fail(f"missing generated cask: {cask_path}")

        cask = cask_path.read_text()
        require_contains(cask, f'sha256 "{expected_macos_sha}"', "generated macOS checksum")
        require_contains(cask, f'sha256 "{expected_linux_sha}"', "generated Linux checksum")
        require_contains(cask, 'cask "foundry@beta" do', "generated beta cask")
        require_contains(cask, "on_macos do", "generated beta cask macOS block")
        require_contains(cask, "on_linux do", "generated beta cask Linux block")
        require_contains(
            cask,
            'conflicts_with cask: ["foundry", "foundry@alpha", "foundry@rc"]',
            "generated beta cask conflicts",
        )

        ruby = shutil.which("ruby")
        if ruby is not None:
            subprocess.run([ruby, "-c", str(cask_path)], check=True, capture_output=True, text=True)


def check_cli_accepts_explicit_sha256_values() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        casks_dir = Path(tmp) / "Casks"
        expected_macos_sha = "b" * 64
        expected_linux_sha = "d" * 64

        result = subprocess.run(
            [
                sys.executable,
                str(GENERATOR),
                "--status",
                "rc4",
                "--version",
                "0.1.0-rc.4",
                "--macos-sha256",
                expected_macos_sha,
                "--linux-sha256",
                expected_linux_sha,
                "--output-dir",
                str(casks_dir),
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )

        cask_path = casks_dir / "foundry@rc.rb"
        require_equal(result.stdout.strip(), str(cask_path), "generator stdout for explicit checksum")
        cask = cask_path.read_text()
        require_contains(cask, f'sha256 "{expected_macos_sha}"', "explicit macOS checksum")
        require_contains(cask, f'sha256 "{expected_linux_sha}"', "explicit Linux checksum")


def find_workflow_wiring_violations(workflow: str) -> list[str]:
    """Return every Homebrew tap wiring violation in the release workflow text."""
    violations: list[str] = []

    required_snippets = [
        "- name: Checkout\n        uses: actions/checkout@v6",
        "name: Update Homebrew tap",
        "if: needs.resolve.outputs.draft == 'false'",
        "HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}",
        "RELEASE_VERSION: ${{ needs.resolve.outputs.release_version }}",
        "RELEASE_STATUS: ${{ needs.resolve.outputs.status }}",
        "Foundry_v${RELEASE_VERSION}_macos.universal.zip",
        "Foundry_v${RELEASE_VERSION}_linux.x86_64.zip",
        "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/cafecito-games/homebrew-tap.git",
        "python3 .github/scripts/generate_homebrew_cask.py",
        '--macos-asset "$macos_asset"',
        '--linux-asset "$linux_asset"',
        'ruby -c "$cask_path"',
        'brew tap cafecito-games/tap "$tap_dir"',
        'brew_tap_dir="$(brew --repository cafecito-games/tap)"',
        'mkdir -p "$brew_tap_dir/Casks"',
        'cp "$cask_path" "$brew_tap_dir/Casks/${cask_token}.rb"',
        'brew audit --cask --tap cafecito-games/tap "$cask_token"',
        "brew untap cafecito-games/tap",
        'git status --porcelain -- "$cask_path"',
        "Brew cask update for ${cask_token} version v${RELEASE_VERSION}",
        "git push origin HEAD:main",
    ]
    missing = [snippet for snippet in required_snippets if snippet not in workflow]
    if missing:
        violations.append(f"release workflow is missing Homebrew tap wiring: {missing}")

    forbidden_snippets = [
        '(cd "$tap_dir" && brew audit --cask "$cask_token")',
        'brew audit --cask "$cask_token"',
        'git diff --quiet -- "$cask_path"',
    ]
    present = [snippet for snippet in forbidden_snippets if snippet in workflow]
    if present:
        violations.append(f"release workflow still contains broken Homebrew tap wiring: {present}")

    audit_sequence = [
        'brew tap cafecito-games/tap "$tap_dir"',
        'brew_tap_dir="$(brew --repository cafecito-games/tap)"',
        'cp "$cask_path" "$brew_tap_dir/Casks/${cask_token}.rb"',
        'brew audit --cask --tap cafecito-games/tap "$cask_token"',
    ]
    if all(snippet in workflow for snippet in audit_sequence):
        positions = [workflow.index(snippet) for snippet in audit_sequence]
        if positions != sorted(positions):
            violations.append(
                "release workflow audits the cask before copying generated content into the Homebrew tap checkout"
            )

    return violations


def check_release_workflow_wires_homebrew_tap_update() -> None:
    violations = find_workflow_wiring_violations(RELEASE_WORKFLOW.read_text())
    if violations:
        fail("\n".join(violations))


def main() -> None:
    generator = load_generator()
    check_status_maps_to_cask_tokens(generator)
    check_status_mapping_rejects_unknown_statuses(generator)
    check_render_stable_cask(generator)
    check_render_alpha_cask(generator)
    check_cli_writes_expected_cask_and_checksum(generator)
    check_cli_accepts_explicit_sha256_values()
    check_release_workflow_wires_homebrew_tap_update()
    print("homebrew cask check passed")


if __name__ == "__main__":
    main()
