# Generated by platform/android/android_host_contract.py. Do not edit by hand.
#
# The native host resolves these members reflectively through JNI, so no compiled
# Java reference keeps them alive. Rules are emitted without allowoptimization so
# R8 cannot rename, remove, inline or staticize them in minified release builds.
# Regenerate with:
#
#     python3 platform/android/android_host_contract.py --emit-keep-rules

-keep,includedescriptorclasses class games.cafecito.foundry.Dictionary {
    <init>();
    void set_keys(java.lang.String[]);
    void set_values(java.lang.Object[]);
}

-keep,includedescriptorclasses class games.cafecito.foundry.Foundry {
    android.app.Activity getActivity();
    boolean checkInternalFeatureSupport(java.lang.String);
    boolean forceQuit(int);
    boolean hasClipboard();
    boolean isDarkMode();
    boolean isDarkModeSupported();
    boolean isInImmersiveMode();
    boolean requestPermission(java.lang.String);
    boolean requestPermissions();
    games.cafecito.foundry.FoundryRenderView getRenderView();
    int createNewFoundryInstance(java.lang.String[]);
    int getAccentColor();
    int getBaseColor();
    java.lang.String getCACertificates();
    java.lang.String getClipboard();
    java.lang.String getInputFallbackMapping();
    java.lang.String[] getFoundryExtensionConfigFiles();
    java.lang.String[] getGrantedPermissions();
    void alert(java.lang.String, java.lang.String);
    void initInputDevices();
    void nativeEnableImmersiveMode(boolean);
    void onFoundryMainLoopStarted();
    void onFoundrySetupCompleted();
    void onFoundryTerminating();
    void restart();
    void setClipboard(java.lang.String);
    void setKeepScreenOn(boolean);
    void setWindowColor(java.lang.String);
    void showDialog(java.lang.String, java.lang.String, java.lang.String[]);
    void showFilePicker(java.lang.String, java.lang.String, int, java.lang.String[]);
    void showInputDialog(java.lang.String, java.lang.String, java.lang.String);
    void vibrate(int, int);
}

-keepclassmembers,includedescriptorclasses class games.cafecito.foundry.FoundryIO {
    boolean hasHardwareKeyboard();
    double getScreenRefreshRate(double);
    float getScaledDensity();
    int getDisplayRotation();
    int getScreenDPI();
    int getScreenOrientation();
    int openURI(java.lang.String);
    int[] getDisplayCutouts();
    int[] getDisplaySafeArea();
    java.lang.String getCacheDir();
    java.lang.String getDataDir();
    java.lang.String getLocale();
    java.lang.String getModel();
    java.lang.String getSystemDir(int, boolean);
    java.lang.String getTempDir();
    java.lang.String getUniqueID();
    void hideKeyboard();
    void setScreenOrientation(int);
    void showKeyboard(java.lang.String, int, int, int, int);
}

-keepclassmembers,includedescriptorclasses class games.cafecito.foundry.FoundryRenderView {
    boolean canCapturePointer();
    void configurePointerIcon(int, java.lang.String, float, float);
    void setPointerIcon(int);
}

-keepclassmembers,includedescriptorclasses class games.cafecito.foundry.io.directory.DirectoryAccessHandler {
    boolean dirExists(int, java.lang.String);
    boolean dirIsDir(int);
    boolean fileExists(int, java.lang.String);
    boolean isCurrentHidden(int);
    boolean makeDir(int, java.lang.String);
    boolean remove(int, java.lang.String);
    boolean rename(int, java.lang.String, java.lang.String);
    int dirOpen(int, java.lang.String);
    int getDriveCount(int);
    java.lang.String dirNext(int);
    java.lang.String getDrive(int, int);
    long getSpaceLeft(int);
    void dirClose(int);
}

-keepclassmembers,includedescriptorclasses class games.cafecito.foundry.io.file.FileAccessHandler {
    boolean fileExists(java.lang.String);
    boolean fileWrite(int, java.nio.ByteBuffer);
    boolean isFileEof(int);
    int fileOpen(java.lang.String, int);
    int fileRead(int, java.nio.ByteBuffer);
    int fileResize(int, long);
    long fileGetPosition(int);
    long fileGetSize(int);
    long fileLastAccessed(java.lang.String);
    long fileLastModified(java.lang.String);
    long fileSize(java.lang.String);
    void fileClose(int);
    void fileFlush(int);
    void fileSeek(int, long);
    void fileSeekFromEnd(int, long);
    void setFileEof(int, boolean);
}

-keepclassmembers,includedescriptorclasses class games.cafecito.foundry.tts.FoundryTTS {
    boolean isPaused();
    boolean isSpeaking();
    int getState();
    java.lang.String[] getVoices();
    void init();
    void pauseSpeaking();
    void resumeSpeaking();
    void speak(java.lang.String, java.lang.String, int, float, float, long, boolean);
    void stopSpeaking();
}

-keepclassmembers,includedescriptorclasses class games.cafecito.foundry.utils.FoundryNetUtils {
    void multicastLockAcquire();
    void multicastLockRelease();
}

-keep,includedescriptorclasses class games.cafecito.foundry.variant.Callable {
    <init>(long);
    long getNativePointer();
}
