#!/usr/bin/env python3
from __future__ import annotations

import hashlib
import importlib.util
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
GENERATOR = REPO_ROOT / ".github/scripts/generate_homebrew_cask.py"
RELEASE_WORKFLOW = REPO_ROOT / ".github/workflows/release.yml"


def fail(message: str) -> None:
    print(message, file=sys.stderr)
    sys.exit(1)


def load_generator():
    if not GENERATOR.is_file():
        fail(f"could not load generator module at {GENERATOR}")

    spec = importlib.util.spec_from_file_location("generate_homebrew_cask", GENERATOR)
    if spec is None or spec.loader is None:
        fail(f"could not load generator module at {GENERATOR}")

    module = importlib.util.module_from_spec(spec)
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def assert_equal(actual, expected, message: str) -> None:
    if actual != expected:
        fail(f"{message}: expected {expected!r}, got {actual!r}")


def assert_contains(haystack: str, needle: str, message: str) -> None:
    if needle not in haystack:
        fail(f"{message}: missing {needle!r}")


def assert_not_contains(haystack: str, needle: str, message: str) -> None:
    if needle in haystack:
        fail(f"{message}: unexpected {needle!r}")


def assert_raises(expected_message: str, callback) -> None:
    try:
        callback()
    except ValueError as exc:
        if expected_message not in str(exc):
            fail(f"wrong error message: expected {expected_message!r} in {exc!r}")
        return
    fail(f"expected ValueError containing {expected_message!r}")


def test_status_maps_to_cask_tokens(generator) -> None:
    cases = {
        "stable": "foundry",
        "alpha1": "foundry@alpha",
        "alpha27": "foundry@alpha",
        "beta1": "foundry@beta",
        "beta12": "foundry@beta",
        "rc1": "foundry@rc",
        "rc8": "foundry@rc",
    }
    for status, expected_token in cases.items():
        assert_equal(generator.token_for_status(status), expected_token, f"token for {status}")


def test_status_mapping_rejects_unknown_statuses(generator) -> None:
    for status in ["dev", "alpha0", "preview1", "rc", "stable1", ""]:
        assert_raises(
            "does not map to a Homebrew cask channel", lambda status=status: generator.token_for_status(status)
        )


def test_render_stable_cask(generator) -> None:
    cask = generator.render_cask(
        token="foundry",
        version="0.1.0",
        sha256="0" * 64,
    )

    required = [
        "# This file was generated by Foundry release automation. DO NOT EDIT.",
        'cask "foundry" do',
        'version "0.1.0"',
        'sha256 "0000000000000000000000000000000000000000000000000000000000000000"',
        'url "https://github.com/cafecito-games/Foundry/releases/download/v#{version}/Foundry_v#{version}_macos.universal.zip"',
        'name "Foundry"',
        'desc "Game engine and editor with Foundry Script"',
        'homepage "https://github.com/cafecito-games/Foundry"',
        'skip "Auto-generated on release."',
        'conflicts_with cask: ["foundry@alpha", "foundry@beta", "foundry@rc"]',
        'app "Foundry.app"',
        'binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"',
    ]
    for snippet in required:
        assert_contains(cask, snippet, "stable cask")

    assert_not_contains(cask, 'conflicts_with cask: ["foundry",', "stable cask should not conflict with itself")
    assert_not_contains(cask, 'conflicts_with cask: "foundry@alpha"', "stable cask should use one conflicts array")


def test_render_alpha_cask(generator) -> None:
    cask = generator.render_cask(
        token="foundry@alpha",
        version="0.1.0-alpha.3",
        sha256="a" * 64,
    )

    required = [
        'cask "foundry@alpha" do',
        'version "0.1.0-alpha.3"',
        'sha256 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"',
        'conflicts_with cask: ["foundry", "foundry@beta", "foundry@rc"]',
        'binary "#{appdir}/Foundry.app/Contents/MacOS/Foundry", target: "foundry"',
    ]
    for snippet in required:
        assert_contains(cask, snippet, "alpha cask")

    assert_not_contains(
        cask, 'conflicts_with cask: ["foundry", "foundry@alpha"', "alpha cask should not conflict with itself"
    )
    assert_not_contains(cask, 'conflicts_with cask: "foundry"', "alpha cask should use one conflicts array")


def test_cli_writes_expected_cask_and_checksum(generator) -> None:
    with tempfile.TemporaryDirectory() as tmp:
        tmp_path = Path(tmp)
        casks_dir = tmp_path / "Casks"
        asset = tmp_path / "Foundry_v0.1.0-beta.2_macos.universal.zip"
        asset.write_bytes(b"fake foundry macos app archive")
        expected_sha = hashlib.sha256(asset.read_bytes()).hexdigest()

        result = subprocess.run(
            [
                sys.executable,
                str(GENERATOR),
                "--status",
                "beta2",
                "--version",
                "0.1.0-beta.2",
                "--asset",
                str(asset),
                "--output-dir",
                str(casks_dir),
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )

        cask_path = casks_dir / "foundry@beta.rb"
        assert_equal(result.stdout.strip(), str(cask_path), "generator stdout")
        if result.stderr:
            fail(f"generator should not write stderr on success: {result.stderr}")
        if not cask_path.is_file():
            fail(f"missing generated cask: {cask_path}")

        cask = cask_path.read_text()
        assert_contains(cask, f'sha256 "{expected_sha}"', "generated checksum")
        assert_contains(cask, 'cask "foundry@beta" do', "generated beta cask")
        assert_contains(
            cask,
            'conflicts_with cask: ["foundry", "foundry@alpha", "foundry@rc"]',
            "generated beta cask conflicts",
        )

        ruby = shutil.which("ruby")
        if ruby is not None:
            subprocess.run([ruby, "-c", str(cask_path)], check=True, capture_output=True, text=True)


def test_cli_accepts_explicit_sha256() -> None:
    with tempfile.TemporaryDirectory() as tmp:
        casks_dir = Path(tmp) / "Casks"
        expected_sha = "b" * 64

        result = subprocess.run(
            [
                sys.executable,
                str(GENERATOR),
                "--status",
                "rc4",
                "--version",
                "0.1.0-rc.4",
                "--sha256",
                expected_sha,
                "--output-dir",
                str(casks_dir),
            ],
            cwd=REPO_ROOT,
            check=True,
            capture_output=True,
            text=True,
        )

        cask_path = casks_dir / "foundry@rc.rb"
        assert_equal(result.stdout.strip(), str(cask_path), "generator stdout for explicit checksum")
        assert_contains(cask_path.read_text(), f'sha256 "{expected_sha}"', "explicit checksum")


def test_release_workflow_wires_homebrew_tap_update() -> None:
    workflow = RELEASE_WORKFLOW.read_text()
    required_snippets = [
        "- name: Checkout\n        uses: actions/checkout@v6",
        "name: Update Homebrew tap",
        "if: needs.resolve.outputs.draft == 'false'",
        "HOMEBREW_TAP_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}",
        "RELEASE_VERSION: ${{ needs.resolve.outputs.release_version }}",
        "RELEASE_STATUS: ${{ needs.resolve.outputs.status }}",
        "Foundry_v${RELEASE_VERSION}_macos.universal.zip",
        "https://x-access-token:${HOMEBREW_TAP_TOKEN}@github.com/cafecito-games/homebrew-tap.git",
        "python3 .github/scripts/generate_homebrew_cask.py",
        'ruby -c "$cask_path"',
        'brew tap cafecito-games/tap "$tap_dir"',
        'brew_tap_dir="$(brew --repository cafecito-games/tap)"',
        'mkdir -p "$brew_tap_dir/Casks"',
        'cp "$cask_path" "$brew_tap_dir/Casks/${cask_token}.rb"',
        'brew audit --cask --tap cafecito-games/tap "$cask_token"',
        "brew untap cafecito-games/tap",
        'git status --porcelain -- "$cask_path"',
        "Brew cask update for ${cask_token} version v${RELEASE_VERSION}",
        "git push origin HEAD:main",
    ]
    missing = [snippet for snippet in required_snippets if snippet not in workflow]
    if missing:
        fail(f"release workflow is missing Homebrew tap wiring: {missing}")

    forbidden_snippets = [
        '(cd "$tap_dir" && brew audit --cask "$cask_token")',
        'brew audit --cask "$cask_token"',
        'git diff --quiet -- "$cask_path"',
    ]
    present = [snippet for snippet in forbidden_snippets if snippet in workflow]
    if present:
        fail(f"release workflow still contains broken Homebrew tap wiring: {present}")

    audit_sequence = [
        'brew tap cafecito-games/tap "$tap_dir"',
        'brew_tap_dir="$(brew --repository cafecito-games/tap)"',
        'cp "$cask_path" "$brew_tap_dir/Casks/${cask_token}.rb"',
        'brew audit --cask --tap cafecito-games/tap "$cask_token"',
    ]
    positions = [workflow.index(snippet) for snippet in audit_sequence]
    if positions != sorted(positions):
        fail("release workflow audits the cask before copying generated content into the Homebrew tap checkout")


def main() -> None:
    generator = load_generator()
    test_status_maps_to_cask_tokens(generator)
    test_status_mapping_rejects_unknown_statuses(generator)
    test_render_stable_cask(generator)
    test_render_alpha_cask(generator)
    test_cli_writes_expected_cask_and_checksum(generator)
    test_cli_accepts_explicit_sha256()
    test_release_workflow_wires_homebrew_tap_update()
    print("homebrew cask tests passed")


if __name__ == "__main__":
    main()
