#!/usr/bin/env python3
"""Generate the FoundryScript TextMate grammar from engine-owned inputs.

The keyword layer is derived from the tokenizer keyword table in
`modules/foundry_script/fs_tokenizer.cpp`, which is the only place that decides what
Foundry Script actually lexes as a keyword. The tokenizer distinguishes two sets that
this generator keeps apart end to end: reserved words, and the built-in numeric
constants `INF`/`NAN`/`PI`/`TAU`. Contextual keywords are lexed as ordinary identifiers
and are therefore never emitted into a keyword alternation; they only reach the grammar
through the narrowly anchored rules in `patterns/constructs.json`.

Everything that does not depend on the keyword table lives in the checked-in pattern
inputs under `patterns/`. `misc/checks/check_foundryscript_tmlanguage.py` fails when the
tokenizer, `GRAMMAR.md` section 2.5, and the generated grammar disagree.

The generated JSON is not committed. It is produced on demand and published as
`foundryscript-tmlanguage-<version>.json` by the release workflow.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path
from typing import Any, NamedTuple

MODULE_DIRECTORY = Path(__file__).resolve().parent
DEFAULT_TOKENIZER = MODULE_DIRECTORY.parent / "fs_tokenizer.cpp"
DEFAULT_PATTERNS_DIRECTORY = MODULE_DIRECTORY / "patterns"

SCOPE_NAME = "source.foundryscript"
GRAMMAR_NAME = "Foundry Script"
FILE_TYPES = ("fs",)

PATTERN_INPUT_FILES = ("lexical.json", "constructs.json")
KEYWORD_SCOPE_FILE = "keyword_scopes.json"

# `KEYWORD("await", Token::AWAIT)` in the tokenizer's `KEYWORDS` X-macro.
KEYWORD_MACRO_ENTRY = re.compile(r'KEYWORD\(\s*"([^"]+)"\s*,\s*Token::(\w+)\s*\)')
NUMERIC_CONSTANT_TOKEN = re.compile(r"^CONST_\w+$")

# The order the root `patterns` list resolves rules in. Ties at the same offset are
# broken by this order, so rules that must lose a tie are declared later: `calls` must
# not claim `if` in `if (x)`, and `type-positions` must not lose `:` to `punctuation`.
ROOT_INCLUDE_ORDER = (
    "comments",
    "strings",
    "annotations",
    "contextual-keywords",
    "keywords",
    "constants",
    "declaration-names",
    "numbers",
    "node-references",
    "calls",
    "type-positions",
    "operators",
    "punctuation",
)

# Pattern inputs may embed this token in a regular expression; the generator replaces it
# with a lookbehind derived from the tokenizer keyword table.
VALUE_ENDING_GUARD = "{{value_ending_guard}}"

# Characters that end a value on their own, before which a `%` is the modulo operator.
VALUE_ENDING_CHARACTERS = r"[\p{L}\p{N}_)\]\"']"

GENERATED_NOTICE = (
    "Generated by modules/foundry_script/grammar/tmlanguage_builder.py from the "
    "Foundry Script tokenizer keyword table and the checked-in pattern inputs beside it. "
    "Do not edit by hand."
)


class KeywordTable(NamedTuple):
    """The two keyword sets the tokenizer distinguishes."""

    reserved: tuple[str, ...]
    numeric_constants: tuple[str, ...]


class GrammarBuildError(RuntimeError):
    """Raised when the inputs cannot produce a well-formed grammar."""


def parse_tokenizer_keywords(source: str) -> KeywordTable:
    """Split the tokenizer's `KEYWORDS` table into reserved words and numeric constants.

    The token type decides the set: `CONST_INF` and friends are keyword tokens that
    denote values, and consumers scope them as language constants rather than keywords.
    """

    reserved: list[str] = []
    numeric_constants: list[str] = []
    for lexeme, token_type in KEYWORD_MACRO_ENTRY.findall(source):
        if NUMERIC_CONSTANT_TOKEN.match(token_type):
            numeric_constants.append(lexeme)
        else:
            reserved.append(lexeme)

    if not reserved or not numeric_constants:
        raise GrammarBuildError("the tokenizer source does not contain a readable KEYWORDS table")

    duplicates = sorted(
        {word for word in reserved + numeric_constants if (reserved + numeric_constants).count(word) > 1}
    )
    if duplicates:
        raise GrammarBuildError(f"the tokenizer KEYWORDS table declares duplicate lexemes: {duplicates}")

    return KeywordTable(tuple(sorted(reserved)), tuple(sorted(numeric_constants)))


def load_pattern_inputs(directory: Path) -> dict[str, Any]:
    """Load every checked-in pattern input, keyed by file name."""

    inputs: dict[str, Any] = {}
    for name in (KEYWORD_SCOPE_FILE, *PATTERN_INPUT_FILES):
        path = directory / name
        if not path.is_file():
            raise GrammarBuildError(f"missing pattern input: {path}")
        inputs[name] = json.loads(path.read_text(encoding="utf-8"))
    return inputs


def alternation(words: tuple[str, ...] | list[str]) -> str:
    """Return a word-boundary alternation with the longest lexemes tried first."""

    ordered = sorted(words, key=lambda word: (-len(word), word))
    return r"\b(?:" + "|".join(ordered) + r")\b"


def build_keyword_rules(reserved: tuple[str, ...], scopes: dict[str, str]) -> list[dict[str, Any]]:
    """Return one alternation rule per distinct scope, in a stable scope order."""

    missing = sorted(set(reserved) - set(scopes))
    if missing:
        raise GrammarBuildError(f"keyword_scopes.json assigns no scope to reserved words: {missing}")
    unknown = sorted(set(scopes) - set(reserved))
    if unknown:
        raise GrammarBuildError(f"keyword_scopes.json scopes words the tokenizer does not reserve: {unknown}")

    grouped: dict[str, list[str]] = {}
    for word in reserved:
        grouped.setdefault(scopes[word], []).append(word)

    return [{"name": scope, "match": alternation(grouped[scope])} for scope in sorted(grouped)]


def build_value_ending_guard(reserved: tuple[str, ...], value_ending: list[str]) -> str:
    """Return the lookbehind that keeps a modulo operator from looking like a node path.

    A `%` starts a unique-name node reference only where the preceding token cannot end a
    value. Whitespace before the `%` does not settle that -- `left %right` is modulo and
    `return %Node` is a node reference -- so the guard admits reserved words that cannot
    end a value and rejects everything else that can, including a trailing run of spaces.
    """

    unknown = sorted(set(value_ending) - set(reserved))
    if unknown:
        raise GrammarBuildError(f"keyword_scopes.json marks non-reserved words as value-ending: {unknown}")

    ordered = sorted(set(reserved) - set(value_ending), key=lambda word: (-len(word), word))
    return (
        r"(?:(?<=\b(?:" + "|".join(ordered) + r")[ \t])"
        rf"|(?<!{VALUE_ENDING_CHARACTERS}[ \t]{{0,4}})(?<!{VALUE_ENDING_CHARACTERS}))"
    )


def substitute(value: Any, guard: str) -> Any:
    """Replace the guard token in every string reachable from a pattern input."""

    if isinstance(value, str):
        return value.replace(VALUE_ENDING_GUARD, guard)
    if isinstance(value, dict):
        return {key: substitute(child, guard) for key, child in value.items()}
    if isinstance(value, list):
        return [substitute(child, guard) for child in value]
    return value


def build_grammar(tokenizer_source: str, pattern_inputs: dict[str, Any]) -> dict[str, Any]:
    """Assemble the whole grammar document."""

    keywords = parse_tokenizer_keywords(tokenizer_source)
    keyword_scopes = pattern_inputs[KEYWORD_SCOPE_FILE]

    literal_constants = keyword_scopes["literal_constants"]
    reserved_literals = sorted(set(literal_constants["words"]) & set(keywords.reserved + keywords.numeric_constants))
    if reserved_literals:
        raise GrammarBuildError(
            f"keyword_scopes.json lists tokenizer keywords as literal constants: {reserved_literals}"
        )

    repository: dict[str, Any] = {
        "keywords": {"patterns": build_keyword_rules(keywords.reserved, keyword_scopes["reserved"])},
        "constants": {
            "patterns": [
                {
                    "name": keyword_scopes["numeric_constants_scope"],
                    "match": alternation(keywords.numeric_constants),
                },
                {
                    "name": literal_constants["scope"],
                    "match": alternation(literal_constants["words"]),
                },
            ]
        },
    }

    guard = build_value_ending_guard(keywords.reserved, keyword_scopes["value_ending_reserved_words"]["words"])
    for name in PATTERN_INPUT_FILES:
        for entry_name, entry in pattern_inputs[name].items():
            if entry_name.startswith("$"):
                continue
            if entry_name in repository:
                raise GrammarBuildError(f"pattern input {name} redefines repository entry {entry_name!r}")
            repository[entry_name] = substitute(entry, guard)

    missing_roots = [name for name in ROOT_INCLUDE_ORDER if name not in repository]
    if missing_roots:
        raise GrammarBuildError(f"the root include order names undefined repository entries: {missing_roots}")

    return {
        "$comment": GENERATED_NOTICE,
        "name": GRAMMAR_NAME,
        "scopeName": SCOPE_NAME,
        "fileTypes": list(FILE_TYPES),
        "patterns": [{"include": f"#{name}"} for name in ROOT_INCLUDE_ORDER],
        "repository": {name: repository[name] for name in sorted(repository)},
    }


def render(grammar: dict[str, Any]) -> str:
    """Serialize the grammar the one way the release artifact is ever written."""

    return json.dumps(grammar, indent=2, ensure_ascii=False, sort_keys=False) + "\n"


def generate(
    tokenizer: Path = DEFAULT_TOKENIZER,
    patterns_directory: Path = DEFAULT_PATTERNS_DIRECTORY,
) -> str:
    """Read the engine-owned inputs and return the serialized grammar."""

    return render(build_grammar(tokenizer.read_text(encoding="utf-8"), load_pattern_inputs(patterns_directory)))


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--output", type=Path, help="write the grammar here instead of stdout")
    parser.add_argument("--tokenizer", type=Path, default=DEFAULT_TOKENIZER, help="path to fs_tokenizer.cpp")
    parser.add_argument(
        "--patterns-dir",
        type=Path,
        default=DEFAULT_PATTERNS_DIRECTORY,
        help="directory holding the checked-in pattern inputs",
    )
    arguments = parser.parse_args(argv)

    try:
        document = generate(arguments.tokenizer, arguments.patterns_dir)
    except (GrammarBuildError, OSError, json.JSONDecodeError) as error:
        print(f"error: {error}", file=sys.stderr)
        return 1

    if arguments.output is None:
        sys.stdout.write(document)
    else:
        arguments.output.parent.mkdir(parents=True, exist_ok=True)
        arguments.output.write_text(document, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
