name: Upload Foundry artifact
description: Upload the Foundry artifact.

inputs:
  name:
    description: The artifact name.
    default: ${{ github.job }}
  path:
    description: The path to upload.
    required: true
    default: bin/*

runs:
  using: composite
  steps:
    - name: Upload Foundry Artifact
      uses: actions/upload-artifact@v7
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}
        # Match this repository's maximum artifact retention.
        retention-days: 1
