import argparse
import pathlib
import re
import sys

VERSION = "foundryproto-fixture 1.0.0"


def _field_type(proto_type):
    if proto_type == "string":
        return "String", '""'
    if proto_type in ("int32", "uint32", "sint32"):
        return "int", "0"
    raise SystemExit(f"unsupported field type: {proto_type}")


def _parse_schema(text):
    message_match = re.search(r"message\s+([A-Za-z_][A-Za-z0-9_]*)\s*\{(?P<body>.*?)\}", text, re.S)
    if not message_match:
        raise SystemExit("schema must contain one message")

    fields = []
    field_pattern = r"^\s*([A-Za-z0-9_]+)\s+([A-Za-z_][A-Za-z0-9_]*)\s*=\s*([0-9]+)\s*;"
    for field_match in re.finditer(field_pattern, message_match.group("body"), re.M):
        field_type, default = _field_type(field_match.group(1))
        fields.append((field_match.group(2), field_type, default))

    return message_match.group(1), fields


def _generate_source(message_name, fields, package):
    class_name = f"{message_name}Proto"
    lines = [
        "# Generated by foundryproto-fixture 1.0.0. Do not edit.",
        f"namespace {package}",
        "",
        f"class_name {class_name} extends RefCounted",
        "",
    ]
    for name, field_type, default in fields:
        lines.append(f"var {name}: {field_type} = {default}")
    lines.append("")
    return "\n".join(lines)


def main():
    if sys.argv[1:] == ["--version"]:
        print(VERSION)
        return 0

    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    parser.add_argument("--manifest", required=True)
    parser.add_argument("--package", required=True)
    args = parser.parse_args()

    schema_path = pathlib.Path(args.input)
    output_path = pathlib.Path(args.output)
    manifest_path = pathlib.Path(args.manifest)

    message_name, fields = _parse_schema(schema_path.read_text(encoding="utf-8"))
    output_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(_generate_source(message_name, fields, args.package), encoding="utf-8")
    manifest_path.write_text(
        f"package={args.package}\nmessages={message_name}\noutputs={output_path.name}\n",
        encoding="utf-8",
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
