#!/usr/bin/env python
from misc.utility.scons_hints import *

import platform_macos_builders

Import("env")

files = [
    "os_macos.mm",
    "foundry_application.mm",
    "foundry_application_delegate.mm",
    "crash_handler_macos.mm",
    "display_server_macos_base.mm",
    "display_server_macos.mm",
    "foundry_button_view.mm",
    "foundry_content_view.mm",
    "foundry_core_cursor.mm",
    "foundry_status_item.mm",
    "foundry_window_delegate.mm",
    "foundry_window.mm",
    "key_mapping_macos.mm",
    "foundry_menu_delegate.mm",
    "foundry_menu_item.mm",
    "foundry_open_save_delegate.mm",
    "native_menu_macos.mm",
    "dir_access_macos.mm",
    "tts_macos.mm",
    "rendering_context_driver_vulkan_macos.mm",
    "gl_manager_macos_angle.mm",
    "gl_manager_macos_legacy.mm",
]

if env.editor_build:
    files += [
        "display_server_embedded.mm",
        "embedded_debugger.mm",
        "embedded_gl_manager.mm",
        "editor/embedded_game_view_plugin.mm",
        "editor/embedded_process_macos.mm",
    ]

if env["library_type"] == "executable":
    if env["use_fuzzer"]:
        # libFuzzer provides its own main(); swap the platform entry point for
        # the FoundryScript fuzzing harness in fuzz_foundry_script_macos.mm.
        files += ["fuzz_foundry_script_macos.mm"]
    else:
        files += ["foundry_main_macos.mm"]
else:
    files += ["libfoundry_macos.mm"]

if env["library_type"] == "static_library":
    prog = env.add_library("#bin/foundry", files)
elif env["library_type"] == "shared_library":
    prog = env.add_shared_library("#bin/foundry", files)
else:
    prog = env.add_program("#bin/foundry", files)

if env["debug_symbols"] and env["separate_debug_symbols"]:
    env.AddPostAction(prog, env.Run(platform_macos_builders.make_debug_macos))

if env["generate_bundle"]:
    env.AlwaysBuild(env.CommandNoCache("generate_bundle", prog, env.Run(platform_macos_builders.generate_bundle)))
