name: GHA

on:
  pull_request:
  push:
    branches:
      - develop
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}|${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  linux-build:
    name: Linux
    uses: ./.github/workflows/linux_builds.yml
